#include "glad/glad.h"
#define GLFW_DLL
#include "GLFW/glfw3.h"
#include <string>
#include <stdlib.h>
#include "init.h"
#include "View/renderer.h"
#include "View/model.h"
#include "Controller/eventHandler.h"
#include "View/ui.h"
#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_opengl3.h"
#include "utils.h"
#include "View/window.h"
#include "View/drawingEntity.h"
